create extension if not exists pgcrypto with schema extensions;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists public.survey_responses (
  id bigint generated by default as identity primary key,
  submitted_at timestamptz not null default now(),
  q1 text not null check (q1 in ('1', '2', '3', '4')),
  q2 text not null check (q2 in ('1', '2', '3', '4')),
  q3 text not null check (q3 in ('1', '2')),
  q4 text not null check (q4 in ('1', '2', '3', '4', '5', '6')),
  q5 text not null check (q5 in ('1', '2', '3')),
  q6 text not null check (q6 in ('1', '2', '3')),
  q7 text not null check (q7 in ('1', '2', '3')),
  q8 text not null check (q8 in ('1', '2', '3', '4', '5')),
  q9 text not null check (q9 in ('1', '2', '3', '4', '5')),
  q10 text not null check (q10 in ('1', '2', '3', '4', '5')),
  q11 text not null check (q11 in ('1', '2', '3', '4', '5')),
  q12 text not null check (q12 in ('1', '2', '3', '4', '5')),
  q13 text not null check (q13 in ('1', '2', '3', '4', '5')),
  q14 text not null check (q14 in ('1', '2', '3', '4', '5')),
  q15 text not null check (q15 in ('1', '2', '3', '4', '5')),
  q16 text not null check (q16 in ('1', '2', '3', '4', '5')),
  q17 text not null check (q17 in ('1', '2', '3', '4', '5')),
  q18 text not null check (q18 in ('1', '2', '3', '4', '5')),
  q19 text not null check (q19 in ('1', '2', '3', '4', '5')),
  q20 text not null check (q20 in ('1', '2', '3', '4', '5')),
  q21 text not null check (q21 in ('1', '2', '3', '4', '5')),
  q22 text not null check (q22 in ('1', '2', '3', '4', '5')),
  q23 text not null check (q23 in ('1', '2', '3', '4', '5')),
  q24 text not null check (q24 in ('1', '2', '3', '4', '5')),
  q25 text not null check (q25 in ('1', '2')),
  q26 text not null check (q26 in ('1', '2')),
  q27 text not null check (q27 in ('1', '2')),
  q28 text not null check (q28 in ('1', '2')),
  q29 text not null check (q29 in ('1', '2')),
  q30 text not null check (q30 in ('1', '2', '3', '4', '5')),
  q31 text not null check (q31 in ('1', '2', '3', '4', '5'))
);

create index if not exists survey_responses_submitted_at_idx
  on public.survey_responses (submitted_at desc);

alter table public.survey_responses enable row level security;
revoke all on table public.survey_responses from public, anon, authenticated;

create table if not exists private.survey_admin_credentials (
  username text primary key,
  salt text not null,
  password_hash text not null,
  updated_at timestamptz not null default now()
);

alter table private.survey_admin_credentials enable row level security;

insert into private.survey_admin_credentials (username, salt, password_hash)
values (
  'admin',
  'c618d676c99e2cfdcd0ed570647f6f1d',
  '605508661c6f9df469d743b64dcb7c0d9c90a79d093073e787cfbed0f9795ee7'
)
on conflict (username) do update
set salt = excluded.salt,
    password_hash = excluded.password_hash,
    updated_at = now();

create table if not exists private.survey_admin_sessions (
  token_hash text primary key,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

alter table private.survey_admin_sessions enable row level security;

create index if not exists survey_admin_sessions_expires_at_idx
  on private.survey_admin_sessions (expires_at);

create table if not exists private.survey_rate_limit_events (
  id bigint generated by default as identity primary key,
  scope text not null,
  client_key text not null,
  created_at timestamptz not null default now()
);

alter table private.survey_rate_limit_events enable row level security;

create index if not exists survey_rate_limit_events_lookup_idx
  on private.survey_rate_limit_events (scope, client_key, created_at desc);

create or replace function private.survey_allowed_values()
returns jsonb
language sql
stable
set search_path = ''
as $$
  select '{
    "Q1":["1","2","3","4"], "Q2":["1","2","3","4"], "Q3":["1","2"], "Q4":["1","2","3","4","5","6"],
    "Q5":["1","2","3"], "Q6":["1","2","3"], "Q7":["1","2","3"],
    "Q8":["1","2","3","4","5"], "Q9":["1","2","3","4","5"], "Q10":["1","2","3","4","5"],
    "Q11":["1","2","3","4","5"], "Q12":["1","2","3","4","5"], "Q13":["1","2","3","4","5"],
    "Q14":["1","2","3","4","5"], "Q15":["1","2","3","4","5"], "Q16":["1","2","3","4","5"],
    "Q17":["1","2","3","4","5"], "Q18":["1","2","3","4","5"], "Q19":["1","2","3","4","5"],
    "Q20":["1","2","3","4","5"], "Q21":["1","2","3","4","5"], "Q22":["1","2","3","4","5"],
    "Q23":["1","2","3","4","5"], "Q24":["1","2","3","4","5"],
    "Q25":["1","2"], "Q26":["1","2"], "Q27":["1","2"], "Q28":["1","2"], "Q29":["1","2"],
    "Q30":["1","2","3","4","5"], "Q31":["1","2","3","4","5"]
  }'::jsonb;
$$;

create or replace function private.survey_rate_limited(
  scope_name text,
  client_key text,
  max_events integer,
  window_seconds integer
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_events integer;
begin
  delete from private.survey_rate_limit_events
  where created_at < now() - interval '1 hour';

  select count(*) into current_events
  from private.survey_rate_limit_events events
  where events.scope = scope_name
    and events.client_key = survey_rate_limited.client_key
    and events.created_at >= now() - make_interval(secs => window_seconds);

  if current_events >= max_events then
    return true;
  end if;

  insert into private.survey_rate_limit_events (scope, client_key)
  values (scope_name, survey_rate_limited.client_key);

  return false;
end;
$$;

create or replace function private.survey_response_count()
returns integer
language sql
security definer
set search_path = ''
as $$
  select count(*)::integer from public.survey_responses;
$$;

create or replace function private.survey_submit_response(payload jsonb, client_key text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  allowed jsonb := private.survey_allowed_values();
  question_id text;
  answer text;
  saved_count integer;
begin
  if private.survey_rate_limited('submit', client_key, 40, 60) then
    return jsonb_build_object('ok', false, 'error', 'too many submissions');
  end if;

  if payload is null or jsonb_typeof(payload) <> 'object' then
    return jsonb_build_object('ok', false, 'error', 'invalid payload');
  end if;

  for question_id in
    select key from jsonb_each(allowed)
    order by substring(key from 2)::integer
  loop
    answer := btrim(coalesce(payload ->> question_id, ''));
    if answer = '' then
      return jsonb_build_object('ok', false, 'error', 'missing fields: ' || question_id);
    end if;
    if not ((allowed -> question_id) ? answer) then
      return jsonb_build_object('ok', false, 'error', 'invalid ' || question_id);
    end if;
  end loop;

  insert into public.survey_responses (
    q1, q2, q3, q4, q5, q6, q7, q8, q9, q10, q11, q12, q13, q14, q15, q16,
    q17, q18, q19, q20, q21, q22, q23, q24, q25, q26, q27, q28, q29, q30, q31
  )
  values (
    payload ->> 'Q1', payload ->> 'Q2', payload ->> 'Q3', payload ->> 'Q4',
    payload ->> 'Q5', payload ->> 'Q6', payload ->> 'Q7', payload ->> 'Q8',
    payload ->> 'Q9', payload ->> 'Q10', payload ->> 'Q11', payload ->> 'Q12',
    payload ->> 'Q13', payload ->> 'Q14', payload ->> 'Q15', payload ->> 'Q16',
    payload ->> 'Q17', payload ->> 'Q18', payload ->> 'Q19', payload ->> 'Q20',
    payload ->> 'Q21', payload ->> 'Q22', payload ->> 'Q23', payload ->> 'Q24',
    payload ->> 'Q25', payload ->> 'Q26', payload ->> 'Q27', payload ->> 'Q28',
    payload ->> 'Q29', payload ->> 'Q30', payload ->> 'Q31'
  );

  saved_count := private.survey_response_count();
  return jsonb_build_object('ok', true, 'count', saved_count);
end;
$$;

create or replace function private.survey_token_hash(token text)
returns text
language sql
stable
set search_path = ''
as $$
  select encode(extensions.digest(token, 'sha256'), 'hex');
$$;

create or replace function private.survey_admin_authorized(token text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  hashed text;
begin
  if coalesce(token, '') = '' then
    return false;
  end if;

  delete from private.survey_admin_sessions where expires_at <= now();
  hashed := private.survey_token_hash(token);

  update private.survey_admin_sessions
  set expires_at = now() + interval '12 hours'
  where token_hash = hashed and expires_at > now();

  return found;
end;
$$;

create or replace function private.survey_admin_login(username text, password text, client_key text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  credential private.survey_admin_credentials%rowtype;
  candidate_hash text;
  token text;
begin
  if private.survey_rate_limited('login', client_key, 8, 600) then
    return jsonb_build_object('ok', false, 'error', 'too many attempts');
  end if;

  select * into credential
  from private.survey_admin_credentials
  where survey_admin_credentials.username = survey_admin_login.username;

  if not found then
    perform pg_sleep(0.25);
    return jsonb_build_object('ok', false, 'error', 'invalid credentials');
  end if;

  candidate_hash := encode(extensions.digest(credential.salt || coalesce(password, ''), 'sha256'), 'hex');
  if candidate_hash <> credential.password_hash then
    perform pg_sleep(0.25);
    return jsonb_build_object('ok', false, 'error', 'invalid credentials');
  end if;

  token := encode(extensions.gen_random_bytes(32), 'hex');
  insert into private.survey_admin_sessions (token_hash, expires_at)
  values (private.survey_token_hash(token), now() + interval '12 hours');

  return jsonb_build_object('ok', true, 'token', token);
end;
$$;

create or replace function private.survey_admin_logout(token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(token, '') <> '' then
    delete from private.survey_admin_sessions
    where token_hash = private.survey_token_hash(token);
  end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function private.survey_admin_clear(token text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.survey_admin_authorized(token) then
    return jsonb_build_object('ok', false, 'error', 'unauthorized');
  end if;
  delete from public.survey_responses where true;
  return jsonb_build_object('ok', true, 'count', 0);
end;
$$;

create or replace function private.survey_admin_export(token text)
returns jsonb
language sql
security definer
set search_path = ''
as $$
  select case
    when not private.survey_admin_authorized(token) then
      jsonb_build_object('ok', false, 'error', 'unauthorized')
    else
      jsonb_build_object(
        'ok', true,
        'rows', coalesce((
          select jsonb_agg(to_jsonb(rows) - 'submitted_sort' order by rows.submitted_sort)
          from (
            select
              submitted_at as submitted_sort,
              to_char(submitted_at at time zone 'Asia/Shanghai', 'YYYY-MM-DD HH24:MI:SS') || ' +0800' as submitted_at,
              q1 as "Q1", q2 as "Q2", q3 as "Q3", q4 as "Q4", q5 as "Q5", q6 as "Q6", q7 as "Q7", q8 as "Q8",
              q9 as "Q9", q10 as "Q10", q11 as "Q11", q12 as "Q12", q13 as "Q13", q14 as "Q14", q15 as "Q15",
              q16 as "Q16", q17 as "Q17", q18 as "Q18", q19 as "Q19", q20 as "Q20", q21 as "Q21", q22 as "Q22",
              q23 as "Q23", q24 as "Q24", q25 as "Q25", q26 as "Q26", q27 as "Q27", q28 as "Q28", q29 as "Q29",
              q30 as "Q30", q31 as "Q31"
            from public.survey_responses
            order by submitted_at
          ) rows
        ), '[]'::jsonb)
      )
  end;
$$;

create or replace function public.survey_response_count()
returns integer
language sql
security invoker
set search_path = ''
as $$ select private.survey_response_count(); $$;

create or replace function public.survey_submit_response(payload jsonb, client_key text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.survey_submit_response(payload, client_key); $$;

create or replace function public.survey_admin_login(username text, password text, client_key text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.survey_admin_login(username, password, client_key); $$;

create or replace function public.survey_admin_logout(token text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.survey_admin_logout(token); $$;

create or replace function public.survey_admin_me(token text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select jsonb_build_object('authenticated', private.survey_admin_authorized(token)); $$;

create or replace function public.survey_admin_clear(token text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.survey_admin_clear(token); $$;

create or replace function public.survey_admin_export(token text)
returns jsonb
language sql
security invoker
set search_path = ''
as $$ select private.survey_admin_export(token); $$;

grant execute on function public.survey_response_count() to anon, authenticated;
grant execute on function public.survey_submit_response(jsonb, text) to anon, authenticated;
grant execute on function public.survey_admin_login(text, text, text) to anon, authenticated;
grant execute on function public.survey_admin_logout(text) to anon, authenticated;
grant execute on function public.survey_admin_me(text) to anon, authenticated;
grant execute on function public.survey_admin_clear(text) to anon, authenticated;
grant execute on function public.survey_admin_export(text) to anon, authenticated;

grant usage on schema private to anon, authenticated;
grant execute on all functions in schema private to anon, authenticated;
